#include "DBoW3/DBoW3.h"
#include <opencv2/core/core.hpp>
#include <opencv2/highgui/highgui.hpp>
#include <opencv2/features2d/features2d.hpp>
#include <iostream>
#include <vector>
#include <string>

using namespace cv;
using namespace std;

/***************************************************
 * 本节演示了如何根据前面训练的字典计算相似性评分
 * 
 * 主要步骤：
 * 1. 读取预训练好的字典 (vocabulary.yml.gz)
 * 2. 读取若干张测试图像
 * 3. 提取图像的 ORB 特征描述子
 * 4. 方式一：直接比较两张图像的 BoW 向量，计算相似度分数
 * 5. 方式二：构建数据库，将图像添加到数据库中，然后进行查询
 * ************************************************/
int main(int argc, char **argv) {
    // -----------------------------------------------------------------------
    // 1. 读取字典
    // -----------------------------------------------------------------------
    cout << "reading database" << endl;
    // DBoW3::Vocabulary 是核心类，用于管理单词和计算向量
    // 构造函数会加载词典文件，构建 K 叉树索引
    DBoW3::Vocabulary vocab("./vocabulary.yml.gz");
    // DBoW3::Vocabulary vocab("./vocab_larger.yml.gz");  // use large vocab if you want: 
    if (vocab.empty()) {
        cerr << "Vocabulary does not exist." << endl;
        return 1;
    }

    // -----------------------------------------------------------------------
    // 2. 读取图像
    // -----------------------------------------------------------------------
    cout << "reading images... " << endl;
    vector<Mat> images;
    // 这里预设读取 data 目录下的 10 张图片 (1.png 到 10.png)
    for (int i = 0; i < 10; i++) {
        string path = "./data/" + to_string(i + 1) + ".png";
        images.push_back(imread(path));
    }

    // NOTE: in this case we are comparing images with a vocabulary generated by themselves, this may lead to overfit.
    // 注意：在这里我们使用这些图像自己训练出来的字典来测试，这在机器学习中属于“训练集当测试集用”，
    // 可能会导致过拟合（得分偏高）。实际应用中，字典通常是用一个独立的大数据集训练的。

    // -----------------------------------------------------------------------
    // 3. 提取 ORB 特征
    // -----------------------------------------------------------------------
    cout << "detecting ORB features ... " << endl;
    Ptr<Feature2D> detector = ORB::create();
    vector<Mat> descriptors;
    for (Mat &image:images) {
        vector<KeyPoint> keypoints;
        Mat descriptor;
        // 计算图像的关键点和描述子
        detector->detectAndCompute(image, Mat(), keypoints, descriptor);
        descriptors.push_back(descriptor);
    }

    // -----------------------------------------------------------------------
    // 4. 方式一：图像 vs 图像 (直接比较)
    // -----------------------------------------------------------------------
    // 我们可以直接比较两张图片计算相似度，或者拿一张图片去数据库里查最像的
    cout << "comparing images with images " << endl;
    for (int i = 0; i < images.size(); i++) {
        // 将第 i 张图的描述子转换成 Bag-of-Words 向量
        // transform 内部流程：
        // 1. 对于描述子中的每个特征，在 K 叉树中查找其对应的单词节点（叶子节点）。
        // 2. 统计每个单词的 TF (Term Frequency) 和 IDF (Inverse Document Frequency)。
        // 3. 计算权重，生成稀疏向量 v1。
        DBoW3::BowVector v1;
            // 将一张图像的描述子集合转换成通过 K 叉树索引和 TF-IDF 加权后的稀疏向量。
        vocab.transform(descriptors[i], v1); // v1 是第 i 张图的 BoW 向量; 将第 i 张图的描述子转换成 Bag-of-Words 向量
        
        for (int j = i; j < images.size(); j++) {
            DBoW3::BowVector v2; // v2 是第 j 张图的 BoW 向量
            vocab.transform(descriptors[j], v2); // 将第 j 张图的描述子转换成 Bag-of-Words 向量
            
            // 计算两个 BoW 向量 v1 和 v2 的得分
            // 这里通常使用 L1 范数或者其他相似度度量（如书中提到的重叠面积）
            double score = vocab.score(v1, v2); // 计算相似度分数,公式为 L1 范数
            cout << "image " << i << " vs image " << j << " : " << score << endl;
        }
        cout << endl;
    }

    // -----------------------------------------------------------------------
    // 5. 方式二：图像 vs 数据库 (Database Query)
    // -----------------------------------------------------------------------
    cout << "comparing images with database " << endl;
    
    // 创建一个数据库，需要基于之前加载的 vocab
    // 参数2: false 表示不使用直接索引 (Direct Index)，只使用逆向索引 (Inverted Index)
    // 参数3: 0 表示使用的层级（默认即可）
    DBoW3::Database db(vocab, false, 0);
    
    // 将所有图像的描述子添加到数据库中
    // 这一步会更新数据库中的逆向索引，记录哪些单词出现在了哪些图像中
    for (int i = 0; i < descriptors.size(); i++)
        db.add(descriptors[i]); // 将第 i 张图的描述子添加到数据库中
        
    cout << "database info: " << db << endl;
    
    // 模拟回环检测过程：拿每一张图去数据库里“查重”
    for (int i = 0; i < descriptors.size(); i++) {
        DBoW3::QueryResults ret; // 存储查询结果的容器
        // query 参数含义：
        // 1. descriptors[i]: 查询图像的描述子
        // 2. ret: 返回的结果，包含图像 ID 和相似度得分
        // 3. 4: max result，最多返回 4 个最相似的结果
        db.query(descriptors[i], ret, 4);      
        cout << "searching for image " << i << " returns " << ret << endl << endl;
    }
    cout << "done." << endl;
}